---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink : /:year
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Kala Bharath's Personal Website"
keywords:    "Kala Bharath Pilla, Kala Bharath PhD, PCS, RDC, Smotifs, Hybrid structure prediction, Protein structure prediction"
description: "Personal website for my research, code and rant "
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:  ## UA-49607422-1 put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#0C0E0D'
  white:     '#FFFFFF'
  blue:      '#256697'
  green:     '#13613A'
  purple:    '#48397C'
  orange:    '#CC1414'
  turquoise: '#CBE9FC'
